### ISSUE TITLE
Create test/example folder for running the pinball model

### ISSUE THREAD

**Issue by lekah** [lekah/pinball#1]
Currently, there's no easy way for a new user to figure out how to start a pinball simulation.
You should have an examples folder to show how to do that

**Comment by chiku-parida** [comment]
@lekah Do you have the documentation now? I want to use PINBALL model. Please tell me how to use this. Thanks!

**Comment by lekah** [comment]
There is an example folder @chiku-parida  . I forgot to close the issue.

**Comment by chiku-parida** [comment]
> There is an example folder @chiku-parida . I forgot to close the issue.

Thank you @lekah for your response. I have already looked in the folder.

1. When I am trying to make the QE5.2 its throwing some error. Is it working for other versions?
2. And I understand the concept behind the model and how this is relevant for solid-electrolytes etc. but could not get exactly the the sequence of calculation that mentioned in the run.sh file, especially about the ~/bin/pinball.ex

Could you please help me with this? I want to implement the model without AiiDA.

**Comment by lekah** [comment]
1. I cannot really help with installation of QE5.2, that is on you with the help of the configure script and 5.2 documentation. The pinball was written into 5.2, but there is an ongoing effort to upgrade it if I'm well informed. @bonfus  can you help out here?
2. That would be the path to the executable you compile (pw.x in this repos' source folder).

**Comment by bonfus** [comment]
Hi there! Yes, I'm working on it, but it is not usable yet and I've slightly changed the implementation focusing almost only on a python module to be used together with an ASE calculator. You can follow the project here:

https://gitlab.com/bonfus/q-e/-/tree/pinball?ref_type=heads

**Comment by chiku-parida** [comment]
Thank you so much @bonfus and @lekah 
I will go through the the gitlab repo. Creating a ASE calculator is a good idea for easy implementation. I will also try to implement with ASE. Thanks again.
